### ISSUE TITLE
Mindmap

### ISSUE THREAD

**Issue by bbelderbos** [BenGriffith/tollway-traffic#1]
Did you make one for this app already?

**Comment by BenGriffith** [comment]
Kinda. I created a high level flow diagram when was discussing ideas with Christo. I need to add more detail/formalize it and pass it along. Will work on this.

**Comment by bbelderbos** [comment]
Nws, an alternative I learned from Erik is: "what is the ideal end user's journey" - you could do that too ...

**Comment by BenGriffith** [comment]
![Image](https://github.com/BenGriffith/tollway-traffic/assets/6089155/f9f22391-d985-49d3-b02f-026153215c5b)

**Comment by BenGriffith** [comment]
Phase 1 complete - messages are created by tollway traffic generator and pushed to pubsub message queue

Phase 2 - process messages using Cloud Functions
Phase 3 - process messages using Cloud Run

Processing should look very similar in nature for both Phase 2 and Phase 3. 
- A few attributes will be taken from the message(s) and stored in redis/in memory datastore to serve high-level analytics in a visualization app. Still deciding on analytics but initial thoughts would be something like: most popular tollway, states with the highest amount of tollway traffic, most popular vehicle model across tollways, etc.
- All attributes will be stored in BigQuery. Plan to design a few tables to help facilitate.

**Comment by bbelderbos** [comment]
Nice, great work. Wonder if it would be beneficial to check in once more on this with Christo, say next month? (if he is available of course)

**Comment by BenGriffith** [comment]
![Image](https://github.com/BenGriffith/tollway-traffic/assets/6089155/261df4f8-5a27-4ec3-8390-9216448db78d)

**Comment by BenGriffith** [comment]
here's an updated mind map. Streaming data generator will route messages to two different subscriptions: push and pull. When message is routed to push subscription it will trigger a cloud function to process/deliver message to redis. For pull subscription, every so often via cron job/cloud scheduler cloud run will pull message and process/deliver to bigquery.

**Comment by bbelderbos** [comment]
Interesting, curious to hear what Christo had to say ...

**Comment by BenGriffith** [comment]
I still need to meet with him. Planning to message him today.
